# Generated by Django 6.0.5 on 2026-08-17 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0002_discount_deleted_at_discount_is_deleted'),
        ('Order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_first_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='Discount.discount')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usage', to='Order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount Usage',
                'verbose_name_plural': 'Discount Usages',
                'constraints': [models.UniqueConstraint(fields=('discount', 'user'), name='unique_discount_per_user')],
            },
        ),
    ]
