# Generated by Django 6.0.5 on 2026-06-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'ProductVariant', 'verbose_name_plural': 'ProductVariants'},
        ),
    ]
